name: trendy_whatsapp_stickers
description: Complete WhatsApp sticker App using Flutter.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_whatsapp_stickers:
  url_launcher: ^5.5.0
  esys_flutter_share: ^1.0.2
  facebook_audience_network: ^0.6.1
  flutter_svg: ^0.17.3+1
  package_info: ^0.4.0+18
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - sticker_packs/1/
    - sticker_packs/2/
    - sticker_packs/3/
    - sticker_packs/4/
    - sticker_packs/sticker_packs.json

  fonts:
   - family: Montserrat
     fonts:
       - asset: assets/fonts/Montserrat-Regular.otf
       - asset: assets/fonts/Montserrat-Bold.otf
         weight: 700
