name: trendy_whatsapp_stickers
description: Complete WhatsApp sticker App using Flutter.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_whatsapp_stickers:
  url_launcher: ^5.5.0
  esys_flutter_share: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/stickers/1
    - assets/stickers/2
    - assets/stickers/3
    - assets/stickers/4
    - assets/stickers/5
    - assets/stickers/6
    - assets/stickers/7
    - assets/stickers/8
    - assets/stickers/9
    - assets/stickers/10
    - assets/stickers/11
    - assets/stickers/12
    - assets/stickers/13
    - assets/stickers/14
    - assets/stickers/15
    - assets/stickers/16
    - assets/stickers/17
    - assets/stickers/18
    - assets/stickers/19
    - assets/stickers/20
    - assets/stickers/21
    - assets/stickers/22
    - assets/stickers/23
    - assets/stickers/24
    - assets/stickers/25
    - assets/stickers/sticker_packs.json
